name: JMH Pre-Integration Tests

on:
  push:
    branches-ignore:
      - master
      - pr/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [8, 11, 17, 21]
        os: [ubuntu-22.04]
      fail-fast: false
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    timeout-minutes: 180

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: ${{ matrix.java }}
        cache: maven
        check-latest: true

    - name: Set up perf (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
        echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
        perf stat echo 1
      if: (runner.os == 'Linux')

    - name: Set up async-profiler (Linux)
      run: |
        curl -L https://github.com/async-profiler/async-profiler/releases/download/v3.0/async-profiler-3.0-linux-x64.tar.gz | tar xzf -
      if: (runner.os == 'Linux')

    - name: Build
      run: |
        mvn clean install -B --file pom.xml -DskipTests
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/async-profiler-3.0-linux-x64/lib/
        java -jar jmh-samples/target/benchmarks.jar -prof async Hello -w 1 -r 1 -f 1
